name: secure_email_viewer
description: A Very Good Project created by Very Good CLI.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  protobuf: ^3.1.0
  crypto: ^3.0.3
  path_provider: ^2.1.2


  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
 
  http: ^1.3.0
  json_serializable: 6.8.0
  jwt_decoder: ^2.0.1
  photo_view: ^0.15.0
  share_plus: ^7.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.2.5

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13

  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/

# Splash screen configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_logo.png
  android: true
  ios: true
  web: false
